### ISSUE TITLE
Endpoint timeout are lost on registry pod restart

### ISSUE THREAD

**Issue by d-uzlov** [networkservicemesh/cmd-registry-k8s#158]
## Expected Behavior

Restarts of registry instance shouldn't significantly affect endpoint automatic deletion when they time out.

## Current Behavior

If registry-k8s is restarted when there are some dead NSEs still registered, they will never be deleted.

## Steps to Reproduce

When in the deployments-k8s repository:
1. Deploy basic setup
2. Deploy Kernek2Kernel example
3. Run `kubectl delete -k .` inside Kernek2Kernel example directory.
4. Immediately run ` kubectl -n nsm-system scale deployment registry-k8s --replicas=0`.
5. Run ` kubectl -n nsm-system scale deployment registry-k8s --replicas=1`
6. Wait few minutes
7. Check output of `kubectl -n nsm-system get nse`

## Context

deployments-k8s git revision 18fdb9cc35395693a81c58c3fef56e523f04ca72

**Comment by denis-tingaikin** [comment]
Nice catch!

I guess it is related to the registry healing scenarious and we need to consider the issue in registry healing.
