### ISSUE TITLE
Issue when register endpoints with same name

### ISSUE THREAD

**Issue by Mixaster995** [networkservicemesh/cmd-registry-k8s#250]
## Description
In interdomain testing for floating scenario, when one example executes after another and using identical name for endpoint they register, tests failing (`TestFloatingKernel2Wireguard2Kernel` fails after `TestFloatingKernel2Vxlan2Kernel` successful, to be precise)
There is workaround for now, that makes everything working - https://github.com/networkservicemesh/deployments-k8s/pull/4070
But this is not desirable behaviour and requires further investigation.

## Steps to recreate

- change name here https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/interdomain/usecases/FloatingKernel2Wireguard2Kernel/nse.yaml#L26 to `icmp-server@my.cluster3`
- start any integration testing(integration-interdomain-k8s or integration-k8s-kind)
- one test `TestFloatingKernel2Wireguard2Kernel` should fail

## Example of failed tests
https://github.com/networkservicemesh/integration-k8s-kind/runs/4530518091?check_suite_focus=true

**Comment by denis-tingaikin** [comment]
Also, I feel we need basically test that the refresh scenario is fine for cmd-registry-k8s.
